language: node_js
env:
  - ASCIIDOCTOR_CORE_VERSION=v1.5.5
  - ASCIIDOCTOR_CORE_VERSION=master
node_js:
  - "4"
  - "6"
  - "node"

jdk:
  - oraclejdk8

before_script:
  - npm install

script:
 - npm run lint
 - npm run package
 - SKIP_BUILD=1 npm run examples

sudo: false
