version: '{build}'
skip_tags: true
skip_commits:
  message: /\[ci skip\]/
clone_depth: 10
environment:
  nodejs_version: 0.12
install:
- git submodule update --init --recursive
- npm install
- npm install -g bower
build_script:
- node npm/appveyor.js
