name: Documentation notify

on:
  push:
    branches:
      - v2.2.x
    paths:
      - 'docs/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notify Netlify
        env:
          NETLIFY_WEBHOOK_URL: ${{ secrets.NETLIFY_WEBHOOK_URL }}
        run: ./scripts/notify.sh
